version: '3.8'

services:
  danbooru:
    image: thorchr96/danbooruui:latest
    #build:
    #  context: .
    #  dockerfile: ./Danbooru.UI/Danbooru.UI/Dockerfile
    ports:
      - "10100:8080" 
      - "10101:8081" 
    restart: unless-stopped