name: .NET Build and Deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore Danbooru.sln
        working-directory: Danbooru

      - name: Build
        run: dotnet build Danbooru.sln --no-restore
        working-directory: Danbooru

      - name: Build Docker Image
        run: docker buildx build --file ./Danbooru.UI/Danbooru.UI/Dockerfile --platform linux/amd64,linux/arm64 --tag your_docker_repo/danbooruui:latest --push .
        working-directory: Danbooru
